-- Clone for India Sales Table
CREATE TABLE sales_in_clone CLONE sales_in;

-- Clone for France Sales Table
CREATE TABLE sales_fr_clone CLONE sales_fr;
CREATE TABLE sales_fr_stage_clone CLONE sales_fr_stage;

-- Clone for US Sales Table
CREATE TABLE sales_us_clone CLONE sales_us;
CREATE TABLE sales_us_stage_clone CLONE sales_us_stage;

-- Clone for consolidated sales table
CREATE TABLE consolidated_sales_clone CLONE consolidated_sales;
TRUNCATE TABLE consolidated_sales_clone;

-- Clone for FACT and DIM TABLES
CREATE OR REPLACE TABLE CUSTOMER_DIM_CLONE CLONE CUSTOMER_DIM;
CREATE OR REPLACE TABLE DATE_DIM_CLONE CLONE DATE_DIM;
CREATE OR REPLACE TABLE PAYMENT_DIM_CLONE CLONE PAYMENT_DIM;
CREATE OR REPLACE TABLE PRODUCT_DIM_CLONE CLONE PRODUCT_DIM;
CREATE OR REPLACE TABLE PROMO_CODE_DIM_CLONE CLONE PROMO_CODE_DIM;
CREATE OR REPLACE TABLE REGION_DIM_CLONE CLONE REGION_DIM;
CREATE OR REPLACE TABLE SALES_FACT_CLONE CLONE SALES_FACT;
TRUNCATE TABLE CUSTOMER_DIM_CLONE;
TRUNCATE TABLE DATE_DIM_CLONE;
TRUNCATE TABLE PAYMENT_DIM_CLONE;
TRUNCATE TABLE PRODUCT_DIM_CLONE;
TRUNCATE TABLE PROMO_CODE_DIM_CLONE;
TRUNCATE TABLE REGION_DIM_CLONE;
TRUNCATE TABLE SALES_FACT_CLONE;