ALTER TABLE PRODUCT_DIM ADD COLUMN MEMORY_STORAGE STRING;
ALTER TABLE PRODUCT_DIM ADD COLUMN BRAND STRING;
ALTER TABLE PRODUCT_DIM ADD COLUMN MODEL_NAME STRING;
ALTER TABLE PRODUCT_DIM ADD COLUMN COLOR STRING;
ALTER TABLE PRODUCT_DIM ADD COLUMN RAM STRING;

UPDATE PRODUCT_DIM
SET 
  BRAND = SPLIT_PART(MOBILE_MODEL, '/', 1),
  MODEL_NAME = SPLIT_PART(MOBILE_MODEL, '/', 2),
  COLOR = SPLIT_PART(MOBILE_MODEL, '/', 3),
  RAM = SPLIT_PART(MOBILE_MODEL, '/', 4),
  MEMORY_STORAGE = SPLIT_PART(MOBILE_MODEL, '/', 5);